import type { Metadata } from "next";
import "./globals.css";
import { usePuterStore } from "@/lib/puter";
import { useEffect } from "react";
import ParentWrapper from "@/components/ParentWrapper";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
        <Script src="https://js.puter.com/v2/" strategy="afterInteractive" />
      </head>
      <body
        className={``}
        style={{ fontFamily: "Inter, sans-serif" }}
      >
        <ParentWrapper>
        {children}
        </ParentWrapper>
      </body>
    </html>
  );
}
